import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.scss";
import { Providers } from "./providers";
import { Sidebar } from "@/components/layout/Sidebar/Sidebar";
import { TopMenu } from "@/components/layout/TopMenu/TopMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="layout">
            <input type="checkbox" id="nav-toggle" className="nav-toggle" />
            <Sidebar />
            <label htmlFor="nav-toggle" className="sidebar-overlay" />
            <div className="layout__main">
              <TopMenu />
              <main className="layout__content">{children}</main>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
