import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.scss";
import { Providers } from "./providers";
import { Sidebar } from "@/components/layout/Sidebar/Sidebar";
import { TopMenu } from "@/components/layout/TopMenu/TopMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Sidebar />
          <TopMenu />
          {children}
        </Providers>
      </body>
    </html>
  );
}
